testing pipeline

diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -4,6 +4,7 @@ on:
   pull_request:
     branches:
       - main
+      - add-cl-test-badge
 
 jobs:
   lint:
@@ -26,3 +27,7 @@ jobs:
 
       - name: Run pre-commit hooks
         run: pre-commit run --all-files
+      - name: This will fail
+        run: |
+          echo "This step will fail intentionally"
+          exit 1
